import { test, expect } from '@playwright/test';
// WOW product information
test('wow', async ({ page }) => {
  await page.goto('https://www.woolworths.com.au/shop/productdetails/716852/quorn-pieces-frozen');
  await expect(page.getByRole('heading', { name: 'Quorn Pieces Frozen 300g' })).toBeVisible();
  await page.goto('https://www.woolworths.com.au/shop/productdetails/6050692/made-with-plants-meat-free-bacon');
  await expect(page.getByRole('heading', { name: 'Made With Plants Meat Free' })).toBeVisible();
  await page.goto('https://www.woolworths.com.au/shop/productdetails/65255/unreal-co-plant-based-beefy-brat-sausages');
  await expect(page.getByRole('heading', { name: 'Unreal Co. Plant Based Beefy' })).toBeVisible();
  await page.goto('https://www.woolworths.com.au/shop/productdetails/65254/unreal-co-plant-based-chick-n-chives-sausages');
  await expect(page.getByRole('heading', { name: 'Unreal Co. Plant Based Chick\'' })).toBeVisible();
  await page.goto('https://www.woolworths.com.au/shop/productdetails/208575/moccona-freeze-dried-instant-coffee-classic-medium-roast');
  await expect(page.getByRole('heading', { name: 'Twinings Live Well Cleanse' })).toBeVisible();
  await page.goto('https://www.woolworths.com.au/shop/productdetails/335073/macro-organic-quinoa');
  await expect(page.getByRole('heading', { name: 'Macro Organic Quinoa 500g' })).toBeVisible();
  await page.goto('https://www.woolworths.com.au/shop/productdetails/499695/macro-white-quinoa');
  await expect(page.getByRole('heading', { name: 'Macro White Quinoa 1kg' })).toBeVisible();
  await page.goto('https://www.woolworths.com.au/shop/productdetails/65575/suntory-boss-coffee-iced-latte');
  await expect(page.getByRole('heading', { name: 'Suntory Boss Coffee Iced' })).toBeVisible();
  await page.goto('https://www.woolworths.com.au/shop/productdetails/212841/vitasoy-soy-milky-lite-long-life-milk-uht');
  await expect(page.getByRole('heading', { name: 'Vitasoy Soy Milky Lite Long' })).toBeVisible();
  await page.goto('https://www.woolworths.com.au/shop/productdetails/867015/yopro-high-protein-yoghurt-vanilla');
  await expect(page.getByRole('heading', { name: 'YoPRO High Protein Yoghurt' })).toBeVisible();
  await page.goto('https://www.woolworths.com.au/shop/productdetails/204716/yopro-high-protein-yoghurt-salted-caramel');
  await expect(page.getByRole('heading', { name: 'YoPRO High Protein Yoghurt' })).toBeVisible();
  await page.goto('https://www.woolworths.com.au/shop/productdetails/729008/woolworths-light-tasty-shredded-cheese');
  await expect(page.getByRole('heading', { name: 'Woolworths Light Tasty' })).toBeVisible();
  await page.goto('https://www.woolworths.com.au/shop/productdetails/780717/woolworths-creamed-cottage-cheese');
  await expect(page.getByRole('heading', { name: 'Woolworths Creamed Cottage' })).toBeVisible();
  await page.goto('https://www.woolworths.com.au/shop/productdetails/240473/simson-s-pantry-low-carb-high-protein-fibre-large-wraps');
  await expect(page.getByRole('heading', { name: 'Simson\'s Pantry Low Carb High' })).toBeVisible();
  await page.goto('https://www.woolworths.com.au/shop/productdetails/326615/neutrogena-ultra-gentle-foaming-face-cleanser');
  await expect(page.getByRole('heading', { name: 'Neutrogena Ultra Gentle' })).toBeVisible();
  await page.goto('https://www.woolworths.com.au/shop/productdetails/345982/finish-dishwasher-deep-cleaner-lemon');
  await expect(page.getByRole('heading', { name: 'Finish Dishwasher Deep' })).toBeVisible();
  await page.goto('https://www.woolworths.com.au/shop/productdetails/829467/finish-concentrated-lemon-sparkle-dishwashing-powder');
  await expect(page.getByRole('heading', { name: 'Finish Concentrated Lemon' })).toBeVisible();
  await page.goto('https://www.woolworths.com.au/shop/productdetails/779653/olay-regenerist-micro-sculpting-night-face-cream-moisturiser');
  await expect(page.getByRole('heading', { name: 'Olay Regenerist Micro' })).toBeVisible();
  await page.goto('https://www.woolworths.com.au/shop/productdetails/258415/olay-moisturising-lotion-complete-defence-sensitive-spf-30');
  await expect(page.getByRole('heading', { name: 'Olay Moisturising Lotion' })).toBeVisible();
});

// Myer product information
test('myr', async ({ page }) => {
  await page.goto('https://www.myer.com.au/p/fujifilm-mini12-instant-camera-in-clay-white-85366');
  await expect(page.getByRole('heading', { name: 'Mini12 Instant Camera in Clay' })).toBeVisible();
  await expect(page.getByRole('paragraph', { name: '$109.65' })).toBeVisible();
  await page.goto('https://www.myer.com.au/p/scanpan-impact-2-piece-fry-pan-set-in-stainless-stel');
  await expect(page.getByRole('heading', { name: 'Impact 2 Piece Fry Pan Set in' })).toBeVisible();
  await expect(page.getByRole('paragraph').filter({ hasText: '$109.00' })).toBeVisible();
  await page.goto('https://www.myer.com.au/p/philips-2000-series-42l-airfryer-l-in-black-na220-00');
  await expect(page.getByRole('heading', { name: '2000 Series 4.2L Airfryer L' })).toBeVisible();
  await expect(page.getByRole('paragraph').filter({ hasText: '$99.00' })).toBeVisible();
  await page.goto('https://www.myer.com.au/p/bonds-4-pack-logo-light-no-show-socks');
  await expect(page.getByRole('heading', { name: 'Mens Logo Lightweight No Show' })).toBeVisible();
  await expect(page.getByRole('paragraph').filter({ hasText: '$19.99' })).toBeVisible();
  await page.goto('https://www.myer.com.au/p/samsonite-classic-leather-slim-backpack-brown');
  await expect(page.getByRole('heading', { name: 'Classic Leather Slim Backpack in Cognac Brown' })).toBeVisible();
  await expect(page.getByRole('paragraph').filter({ hasText: '$179.40' })).toBeVisible();
  await page.goto('https://www.myer.com.au/p/scanpan-impact-26cm-fry-pan-908154370-1');
  await expect(page.getByRole('heading', { name: 'Impact Fry Pan 26cm in Stainless Steel' })).toBeVisible();
  await expect(page.getByRole('paragraph').filter({ hasText: '$64.50' })).toBeVisible();
});